# Generated by Django 3.1.7 on 2024-09-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_auto_20240906_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default='000000000', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
